#!/bin/bash

set -e
set -o pipefail

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source /opt/resource/common.sh

# Read inputs
payload=$(mktemp $TMPDIR/helm-resource-request.XXXXXX)
cat > $payload <&0

# Prepare
setup_resource $payload

# Parse parameters
namespace=$(jq -r '.source.namespace // "default"' < $payload)
release=$(jq -r '.source.release // ""' < $payload)
release_overwrite=$(jq -r '.params.release // ""' < $payload)
current_release=$(jq -r '.version.release' < $payload || true)


echo "$release ----- $release_overwrite ------ $current_release" 

if [ -f "$source/$release_overwrite" ]; then
  release=$(cat $source/$release_overwrite)
elif [ -n "$release_overwrite" ]; then
  release=$release_overwrite
fi

echo "after first if: $release "

if [ -z "$release" ]; then
  release="$current_release"
fi

echo "after second if: $release "

if [ "$release"] ; then
  echo "$release was true"
  revision=$($helm_bin status --namespace $namespace $release -o json 2>/dev/null | jq '.version')
  echo "revision: $revision"
  if [ $? -ne 0 ] ; then
    echo "helm status failed"
    revision=0
  fi
  echo $revision | jq -R '.' | jq -s "map({\"revision\": ., \"release\": \"$release\"})" >&3
  exit 0
fi

echo "everything else failed"
# we only get here if everything else fails.
echo "ReleaseNotFound" | jq -R '.' | jq -s "map({\"revision\": ., \"release\": \"$release\"})" >&3
